% _________________________________________________________________________
% Import Data
% -------------------------------------------------------------------------
TurbulenceData      = load('RawData/TurbulenceData4.txt');
PowerArrayData      = load('RawData/PowerArray.txt');
Power4ArrayData     = load('RawData/PowerArray_yaw_4.txt');
TimeProfitX         = load('RawData/Time-1.txt');
TimeProfitY         = load('RawData/Profit-1.txt');
% _________________________________________________________________________
% Plot Turbulence
% -------------------------------------------------------------------------
TurbulenceX     = TurbulenceData(:,1)./1000;
TurbulenceY     = TurbulenceData(:,2);

Figure1 = NeatPlot(TurbulenceX', TurbulenceY',...
                [],...
                [],...
                [],...
                ["WM6"],...
                '',...
                [1 1],...
                {"Time [\times 10^3 s]", "Turbulence Intensity [-]"},...
                "Turb6R");
% Figure1.SavePlot()
% _________________________________________________________________________
% Plot Power
% -------------------------------------------------------------------------
X     = PowerArrayData(:,1);
Y     = [PowerArrayData(:,2) Power4ArrayData(:,2)];

Figure1 = NeatPlot(X', Y',...
                [],...
                [],...
                [],...
                {'Theoretical Ceiling', 'WM6'},...
                '',...
                [1 1],...
                {'Windspeed [m/s]', 'Power Generated [W]'},...
                'Power6R');
% _________________________________________________________________________
% Revenue Plot
% -------------------------------------------------------------------------

X     = TimeProfitX;
Zero = zeros(length(TimeProfitX), 1);
Y     = [TimeProfitY Zero];

Figure1 = NeatPlot(X', Y',...
                [],...
                [],...
                [],...
                ["Optimal Location Profit", "Breakeven Point"],...
                '',...
                [1 1],...
                {"Time [years]" ,"Balance [euro]" },...
                "Profit6");            



