% _________________________________________________________________________
% Import Data
% -------------------------------------------------------------------------
TurbulenceData      = load('RawData/TurbulenceData4.txt');
PowerArrayData      = load('RawData/PowerArray.txt');
Power4ArrayData     = load('RawData/PowerArray_yaw_4.txt');
% _________________________________________________________________________
% Plot Turbulence
% -------------------------------------------------------------------------

Figure1 = NeatPlot(x_values, y_values,...
                domain,...
                [],...
                [10 0],...
                legend,...
                title,...
                scale,...
                ax_label,...
                save_n);
Figure1.SavePlot()

